// Knowledge-pack fact test: each item is a short pack passage (what a downloaded pack would hold), a question
// that paraphrases it (so plain word matching is not enough every time) and a code-checkable answer.
// Groups: eg = Egypt, cr = cranes / engineering, gen = general. Arabic questions are marked ar.
export const FACTS = [
  // ---- Egypt ----
  ["eg", "The Aswan High Dam was completed in 1970; it is about 3,830 metres long and 111 metres high and created Lake Nasser.", "In which year was the big dam at Aswan finished?", /1970/],
  ["eg", "Lake Nasser, the reservoir behind the Aswan High Dam, is about 550 km long; roughly 83% of it lies in Egypt and the rest in Sudan, where it is called Lake Nubia.", "What is the Sudanese part of Lake Nasser called?", /nubia/i],
  ["eg", "The Suez Canal opened on 17 November 1869 and links Port Said on the Mediterranean with Port Tewfik at Suez on the Red Sea; it is about 193 km long.", "How long is the Suez Canal in kilometres?", /193/],
  ["eg", "The New Suez Canal, a 35 km parallel channel plus widening of 37 km, was opened in August 2015.", "In what year did the New Suez Canal expansion open?", /2015/],
  ["eg", "The Great Pyramid of Giza was built for the pharaoh Khufu around 2560 BC and was originally about 146.6 metres tall.", "For which king was the Great Pyramid built?", /khufu|cheops/i],
  ["eg", "The Cairo Metro opened its first line (Helwan to El Marg) in 1987; it was the first full metro system in Africa and the Arab world.", "When did Cairo's underground railway start running?", /1987/],
  ["eg", "Cairo Metro Line 3 runs from Adly Mansour in the east to Rod El Farag Corridor and Cairo University in the west.", "Which station is the eastern end of Cairo Metro Line 3?", /adly mansour/i],
  ["eg", "The Egyptian pound (EGP) is divided into 100 piastres (qirsh).", "How many piastres make one Egyptian pound?", /100|hundred/i],
  ["eg", "The Grand Egyptian Museum near the Giza pyramids opened fully to the public on 4 November 2025 and displays the complete Tutankhamun collection.", "In which year did the Grand Egyptian Museum fully open?", /2025/],
  ["eg", "Tutankhamun's tomb (KV62) in the Valley of the Kings was discovered by Howard Carter in November 1922.", "Who found Tutankhamun's tomb?", /carter/i],
  ["eg", "The Bibliotheca Alexandrina, the new library of Alexandria, was inaugurated on 16 October 2002.", "When was the modern Alexandria library inaugurated?", /2002/],
  ["eg", "Mount Catherine (Gabal Katrina) in South Sinai is the highest mountain in Egypt at about 2,629 metres.", "What is Egypt's highest peak?", /catherine|katrina|كاترين/i],
  ["eg", "The Qattara Depression in the Western Desert reaches about 133 metres below sea level, the lowest point in Egypt.", "How far below sea level is the lowest point of the Qattara Depression?", /133/],
  ["eg", "Egypt's country calling code is +20; Cairo landlines use area code 2.", "What is Egypt's international dialling code?", /\+?20\b/],
  ["eg", "The emergency ambulance number in Egypt is 123; police is 122 and fire is 180.", "Which number do you call for an ambulance in Egypt?", /123/],
  ["eg", "Egypt's fire brigade emergency number is 180.", "What number reaches the fire service in Egypt?", /180/],
  ["eg", "The Nile is about 6,650 km long; its two main branches, the White Nile and the Blue Nile, meet at Khartoum.", "In which city do the White and Blue Nile join?", /khartoum/i],
  ["eg", "Abu Simbel's two temples were moved 65 metres higher between 1964 and 1968 to save them from Lake Nasser.", "By how many metres were the Abu Simbel temples raised?", /65/],
  ["eg", "The sun festival at Abu Simbel happens twice a year, around 22 February and 22 October, when sunlight reaches the inner sanctuary.", "On which two dates does the sun light the inner sanctuary of Abu Simbel?", /22 ?feb[\s\S]*22 ?oct|22 ?oct[\s\S]*22 ?feb|february 22[\s\S]*october 22|october 22[\s\S]*february 22/i],
  ["eg", "The Benban Solar Park near Aswan has a capacity of about 1.65 GW and was one of the largest solar installations in the world when completed in 2019.", "What is the capacity of the Benban solar park?", /1[.,]65|1650/],
  ["eg", "Egypt's New Administrative Capital lies about 45 km east of Cairo; its Iconic Tower is about 394 metres tall, the tallest building in Africa.", "How tall is the Iconic Tower in the New Administrative Capital?", /39[34]/],
  ["eg", "The El Dabaa nuclear power plant on the Mediterranean coast is planned with four VVER-1200 reactors of 1,200 MW each.", "How many reactors are planned at El Dabaa?", /\b4\b|four/i],
  ["eg", "Egypt's 2014 constitution sets the presidential term at six years since the 2019 amendments.", "How long is an Egyptian presidential term after the 2019 amendments?", /\b6\b|six/i],
  ["eg", "Egyptian Labour Law No. 14 of 2025 replaced Law 12 of 2003.", "Which labour law did Law 14 of 2025 replace?", /12 of 2003|12\/2003|2003/],
  ["eg", "Under Egyptian traffic law, a private car driving licence is valid for 10 years.", "How many years is a private car licence valid in Egypt?", /\b10\b|ten/i],
  ["eg", "The Cairo International Airport code is CAI; Borg El Arab airport in Alexandria is HBE.", "What is the airport code of Borg El Arab airport?", /HBE/],
  ["eg", "Siwa Oasis lies about 50 km east of the Libyan border and is known for the Temple of the Oracle of Amun.", "Which oracle's temple is in Siwa?", /amun|amon|آمون/i],
  ["eg", "Ras Mohammed National Park, at the southern tip of Sinai, was declared Egypt's first national park in 1983.", "What was Egypt's first national park?", /ras moham+ed|راس محمد|رأس محمد/i],
  ["eg", "Wadi El Hitan (Whale Valley) in Fayoum is a UNESCO World Heritage Site with fossils of early whales.", "What fossils is Wadi El Hitan famous for?", /whale/i],
  ["eg", "The Cairo Tower in Zamalek is 187 metres tall and was completed in 1961.", "How tall is the Cairo Tower?", /187/],
  // Arabic questions (Egypt)
  ["eg", "The Aswan High Dam was completed in 1970.", "السد العالي خلص امتى؟", /1970|١٩٧٠/, "ar"],
  ["eg", "The emergency ambulance number in Egypt is 123.", "رقم الإسعاف في مصر كام؟", /123|١٢٣/, "ar"],
  ["eg", "The Cairo Tower in Zamalek is 187 metres tall.", "برج القاهرة طوله كام متر؟", /187|١٨٧/, "ar"],
  ["eg", "Mount Catherine is the highest mountain in Egypt at about 2,629 metres.", "ارتفاع جبل كاترين كام متر؟", /2[,.]?629|٢٦٢٩|٢٬٦٢٩/, "ar"],
  ["eg", "The Suez Canal opened on 17 November 1869.", "قناة السويس اتفتحت سنة كام؟", /1869|١٨٦٩/, "ar"],
  ["eg", "Cairo Metro opened its first line in 1987.", "مترو القاهرة بدأ سنة كام؟", /1987|١٩٨٧/, "ar"],
  ["eg", "Tutankhamun's tomb was discovered by Howard Carter in 1922.", "مقبرة توت عنخ آمون اتكشفت سنة كام؟", /1922|١٩٢٢/, "ar"],
  ["eg", "Egypt's fire brigade emergency number is 180.", "رقم المطافي في مصر؟", /180|١٨٠/, "ar"],
  ["eg", "Abu Simbel's temples were moved 65 metres higher between 1964 and 1968.", "معابد أبو سمبل اترفعت كام متر؟", /65|٦٥/, "ar"],
  ["eg", "The Benban Solar Park near Aswan has a capacity of about 1.65 GW.", "قدرة محطة بنبان الشمسية كام؟", /1[.,]65|1650|١[.,٫]٦٥|١٦٥٠/, "ar"],
  // ---- cranes / engineering ----
  ["cr", "In ASME B30.5 mobile crane practice, the rated load chart capacity at a given radius already includes a stability margin: 85% of tipping load for crawler cranes and 75% for cranes on outriggers (SAE J765/ISO 4305).", "What percentage of tipping load is allowed for a mobile crane on outriggers under the common rating rule?", /75/],
  ["cr", "For crawler cranes, rated loads are limited to 85% of the tipping load.", "Crawler cranes may lift up to what percentage of the tipping load?", /85/],
  ["cr", "Wire rope with a 6x36 construction has 6 strands of 36 wires each; more wires give better fatigue resistance but less abrasion resistance than 6x19.", "Compared with 6x19, does 6x36 wire rope have better fatigue or better abrasion resistance?", /fatigue/i],
  ["cr", "A common rule in crane wire rope inspection is to remove the rope from service if there are 6 randomly distributed broken wires in one rope lay or 3 broken wires in one strand in one lay (running ropes, ASME B30.5).", "How many randomly distributed broken wires in one lay mean a running rope must be retired?", /\b6\b|six/i],
  ["cr", "The minimum design factor for running ropes on mobile cranes is 3.5 (ASME B30.5); for rotation-resistant rope it is 5.", "What is the minimum design factor for rotation-resistant rope on a mobile crane?", /\b5\b|five/i],
  ["cr", "The minimum design factor for standard running ropes on mobile cranes is 3.5.", "What design factor is required for ordinary running wire rope on a mobile crane?", /3[.,]5/],
  ["cr", "Anemometer rule of thumb: most mobile crane manufacturers stop lifting when the wind speed exceeds 20 m/s (about 72 km/h), with lower limits for large sail-area loads.", "Above what wind speed do most mobile crane makers say to stop lifting, in m/s?", /20/],
  ["cr", "A crane's load moment is the load multiplied by the radius; a 10 tonne load at 8 m radius gives 80 tonne-metres.", "What is the load moment of a 10 t load at 8 m radius?", /80/],
  ["cr", "Outrigger pad bearing pressure is the outrigger force divided by the pad area; 30 tonnes on a 1 m x 1 m mat gives 30 t/m2 (about 294 kPa).", "What pressure in t/m2 does a 30 t outrigger force make on a 1 m by 1 m mat?", /30/],
  ["cr", "Firm dry clay typically allows about 200 kPa bearing pressure, compacted gravel about 400 kPa, and soft clay under 75 kPa (BS 7121 guidance tables).", "Roughly what allowable bearing pressure does compacted gravel give, in kPa?", /400/],
  ["cr", "A two-leg sling at a 60-degree included angle (30 degrees each from vertical) carries each leg about 0.577 times the load.", "With a two-leg sling and 60 degrees between the legs, what fraction of the load does each leg carry?", /0[.,]577|0[.,]58/],
  ["cr", "At a 120-degree included sling angle each leg of a two-leg sling carries a force equal to the full load.", "At 120 degrees between the legs, what force does each sling leg carry?", /full|1[.,]0|equal|whole|100 ?%/i],
  ["cr", "In the standard crane hand signals, 'emergency stop' is shown with both arms extended, palms down, moving the arms back and forth horizontally.", "How do you signal an emergency stop to a crane operator?", /both arms|arms (extended|out)/i],
  ["cr", "Steel S355 has a minimum yield strength of 355 MPa for thicknesses up to 16 mm.", "What is the minimum yield strength of S355 steel?", /355/],
  ["cr", "Structural steel density is about 7,850 kg/m3.", "What is the density of structural steel in kg per cubic metre?", /7[,.]?850/],
  ["cr", "Concrete density is about 2,400 kg/m3 for normal-weight concrete (2,500 when reinforced).", "What is the density of normal concrete?", /2[,.]?400/],
  ["cr", "The modulus of elasticity of steel is about 200-210 GPa.", "What is the Young's modulus of steel in GPa?", /20[0-9]|210/],
  ["cr", "A hook block with 4 parts of line divides the line pull by 4 (ignoring friction), so a 20 t load needs about 5 t line pull.", "With 4 parts of line, what line pull lifts a 20 tonne load ignoring friction?", /\b5\b|five/i],
  ["cr", "Shackle working load limits are stamped on the bow; a 3/4 inch Grade S bow shackle is rated 4.75 t.", "What is the WLL of a 3/4 inch bow shackle?", /4[.,]75/],
  ["cr", "Tower crane slewing rings are typically inspected for bolt pre-tension at commissioning and after the first 300 operating hours, then periodically.", "After how many operating hours are slewing ring bolts re-checked first?", /300/],
  ["cr", "Lifting operations in the UK are governed by LOLER 1998, which requires thorough examination of lifting accessories every 6 months.", "How often must lifting accessories be thoroughly examined under LOLER?", /6 months|six months|every 6/i],
  ["cr", "Under LOLER, lifting equipment not used to lift people must be thoroughly examined at least every 12 months.", "How often must lifting equipment that does not lift people be examined under LOLER?", /12 months|twelve months|year/i],
  ["cr", "The weight of 1 cubic metre of water is 1 tonne; a 5 m3 tank of water weighs about 5 tonnes plus the tank.", "How heavy is 5 cubic metres of water?", /\b5\b|five/i],
  ["cr", "A tandem lift (two cranes sharing a load) is often limited to 75% of each crane's chart capacity as a planning rule.", "In a two-crane lift, what share of each crane's chart capacity is a common planning limit?", /75/],
  ["cr", "An 'engineered lift' or critical lift is usually defined as one over 75% of the crane's rated capacity at that radius, or with people, or over occupied areas.", "Above what percentage of rated capacity does a lift become a critical lift in many company rules?", /75/],
  ["cr", "The safe working distance from overhead power lines up to 50 kV is 10 feet (about 3 metres) under OSHA 1926.1408.", "What minimum clearance from power lines up to 50 kV does OSHA require for cranes?", /10 ?(ft|feet|foot)|3 ?m/i],
  ["cr", "The centre of gravity of a uniform beam is at its mid-length.", "Where is the centre of gravity of a uniform beam?", /mid|middle|centre|center|half/i],
  ["cr", "1 kN is about 0.102 tonnes-force; 1 tonne-force is 9.81 kN.", "How many kN is one tonne-force?", /9[.,]8/],
  ["cr", "Bolt grade 8.8 means an ultimate tensile strength of 800 MPa and a yield of 80% of that (640 MPa).", "What is the yield strength of a grade 8.8 bolt?", /640/],
  ["cr", "Grade 10.9 bolts have a tensile strength of 1,000 MPa and yield of 900 MPa.", "What is the tensile strength of a 10.9 bolt?", /1[,.]?000/],
  // Arabic (cranes)
  ["cr", "Mobile cranes on outriggers may lift up to 75% of the tipping load.", "الونش على الرجول يرفع كام في المية من حمل الانقلاب؟", /75|٧٥/, "ar"],
  ["cr", "Structural steel density is about 7,850 kg/m3.", "كثافة الحديد الإنشائي كام كيلو للمتر المكعب؟", /7[,.]?850|٧٨٥٠|٧٬٨٥٠/, "ar"],
  ["cr", "A crane's load moment is the load multiplied by the radius; a 10 tonne load at 8 m radius gives 80 tonne-metres.", "عزم حمل ١٠ طن على نصف قطر ٨ متر كام؟", /80|٨٠/, "ar"],
  ["cr", "1 tonne-force is 9.81 kN.", "الطن قوة يساوي كام كيلو نيوتن؟", /9[.,]8|٩[.,٫]٨/, "ar"],
  ["cr", "Bolt grade 8.8 has a yield of 640 MPa.", "مسمار جريد ٨٫٨ إجهاد الخضوع بتاعه كام؟", /640|٦٤٠/, "ar"],
  // ---- general ----
  ["gen", "Mount Everest's official height, agreed by Nepal and China in 2020, is 8,848.86 metres.", "What is the official height of Everest announced in 2020?", /8[,.]?848/],
  ["gen", "The speed of light in vacuum is exactly 299,792,458 metres per second.", "What is the exact speed of light in m/s?", /299[,.\s]?792[,.\s]?458/],
  ["gen", "Water boils at 100 C at sea level; at the top of Everest it boils at about 70 C.", "Around what temperature does water boil on the summit of Everest?", /7[01]/],
  ["gen", "The International Space Station orbits at roughly 400 km altitude and circles Earth about every 90 minutes.", "How long does the ISS take for one orbit?", /9[0-3]/],
  ["gen", "The human body has 206 bones in adults.", "How many bones does an adult human have?", /206/],
  ["gen", "The Burj Khalifa in Dubai is 828 metres tall.", "How tall is the Burj Khalifa?", /828/],
  ["gen", "The Pacific is the largest ocean, covering about 165 million square kilometres.", "Roughly how large is the Pacific Ocean in million km2?", /16[0-9]/],
  ["gen", "The chemical symbol for tungsten is W, from its old name wolfram.", "What is tungsten's chemical symbol?", /\bW\b/],
  ["gen", "Insulin was first used to treat a diabetic patient in January 1922 in Toronto.", "In which year was insulin first given to a patient?", /1922/],
  ["gen", "The first iPhone was released in the United States on 29 June 2007.", "When did the first iPhone go on sale?", /2007/],
  ["gen", "UTF-8 encodes Arabic letters in 2 bytes each.", "How many bytes does UTF-8 use for an Arabic letter?", /\b2\b|two/i],
  ["gen", "A marathon is 42.195 km long.", "How long is a marathon in km?", /42[.,]195/],
  ["gen", "The Arabic alphabet has 28 letters.", "How many letters are in the Arabic alphabet?", /28/],
  ["gen", "Light from the Sun takes about 8 minutes 20 seconds to reach Earth.", "How long does sunlight take to reach Earth?", /8 ?min|8[.:]3|eight min|499|500 ?s/i],
  ["gen", "The FIFA World Cup 2026 is hosted by the United States, Canada and Mexico with 48 teams.", "How many teams play in the 2026 World Cup?", /48/],
  ["gen", "Egypt's Mohamed Salah joined Liverpool from Roma in 2017.", "From which club did Mohamed Salah join Liverpool?", /roma/i],
  ["gen", "The Hubble Space Telescope was launched in April 1990.", "When was Hubble launched?", /1990/],
  ["gen", "The James Webb Space Telescope was launched on 25 December 2021.", "On what date did the James Webb telescope launch?", /25 ?dec|december 25|2021-12-25/i],
  ["gen", "The deepest point in the ocean, Challenger Deep in the Mariana Trench, is about 10,935 metres deep.", "How deep is Challenger Deep?", /10[,.]?9\d\d|11[,.]?0\d\d/],
  ["gen", "A standard A4 sheet measures 210 mm by 297 mm.", "What are the dimensions of A4 paper?", /210[\s\S]*297/],
  ["gen", "The ozone layer is mostly in the stratosphere at about 15-35 km altitude.", "In which atmospheric layer is most ozone found?", /stratosphere/i],
  ["gen", "The Rosetta Stone was found in 1799 near the town of Rashid (Rosetta) in Egypt and is kept in the British Museum.", "Which museum holds the Rosetta Stone?", /british museum/i],
  ["gen", "Lithium-ion batteries degrade fastest when kept at 100% charge and high temperature; storing at about 40-60% charge is recommended.", "At what charge level is it best to store a lithium-ion battery?", /40|50|60/],
  ["gen", "USB-C Power Delivery 3.1 Extended Power Range allows up to 240 W.", "What is the maximum power of USB PD 3.1 EPR?", /240/],
  // Arabic (general)
  ["gen", "The Arabic alphabet has 28 letters.", "الحروف العربية كام حرف؟", /28|٢٨/, "ar"],
  ["gen", "A marathon is 42.195 km long.", "الماراثون طوله كام كيلو؟", /42[.,]195|٤٢[.,٫]١٩٥/, "ar"],
  ["gen", "The human body has 206 bones in adults.", "جسم الإنسان البالغ فيه كام عضمة؟", /206|٢٠٦/, "ar"],
  ["gen", "The Burj Khalifa in Dubai is 828 metres tall.", "برج خليفة طوله كام؟", /828|٨٢٨/, "ar"],
  ["gen", "The Rosetta Stone is kept in the British Museum.", "حجر رشيد موجود في أنهي متحف؟", /البريطاني|british/i, "ar"],
];
