/* ---- v5.42 — Fit: the big food table (per 100 g, or 100 ml for drinks) ----------------------------------
   [id, "English|aliases", "Arabic|aliases", kcal, protein, carbs, fat, fibre, {portion: grams}, group]
   Values from standard composition tables (USDA FoodData Central, the Egyptian NFSI food composition
   tables, McCance & Widdowson), rounded; cooked dishes are typical home recipes. Added to fit.js FOODS. */
export const MORE_FOODS = [
  // ---- Egyptian home cooking ----
  ["fatta", "Fatta (rice, bread, meat)", "فتة|فتة لحمة", 190, 9, 20, 8.5, 0.8, { plate: 350, bowl: 300 }, "dishes"],
  ["roqaq", "Roqaq with minced meat", "رقاق|رقاق باللحمة", 290, 11, 28, 15, 1, { piece: 150, square: 150 }, "dishes"],
  ["kofta-tray", "Kofta tray with potatoes (siniyet kofta)", "صينية كفتة|كفتة بالبطاطس", 170, 9, 12, 9.5, 1.5, { plate: 300 }, "dishes"],
  ["potato-tray", "Potato tray with tomato (siniyet batates)", "صينية بطاطس|بطاطس بالصلصة", 120, 3, 15, 5.5, 2, { plate: 300 }, "dishes"],
  ["chicken-rice-oven", "Oven chicken with rice", "فراخ بالفرن|فراخ بالرز", 175, 13, 15, 6.5, 0.5, { plate: 350 }, "dishes"],
  ["kawareh", "Cow trotters soup (kawareh)", "كوارع|شوربة كوارع", 120, 12, 2, 7, 0, { bowl: 300 }, "dishes"],
  ["mombar", "Mombar (stuffed sausage)", "ممبار", 260, 7, 25, 15, 1, { piece: 50, plate: 200 }, "dishes"],
  ["kebda-iskandarani", "Alexandrian liver", "كبدة إسكندراني|كبدة اسكندراني", 195, 22, 6, 9, 1, { plate: 200, portion: 150 }, "dishes"],
  ["sogo2", "Sausage sandwich (sogo2)", "سجق|ساندوتش سجق", 280, 12, 22, 16, 1.5, { sandwich: 170, piece: 170 }, "dishes"],
  ["hawawshi-alex", "Alexandrian hawawshi", "حواوشي إسكندراني", 300, 13, 22, 18, 1.5, { piece: 250 }, "dishes"],
  ["fiteer-honey", "Feteer with honey", "فطير بالعسل", 400, 6, 50, 19, 1.2, { piece: 120 }, "sweets"],
  ["kishk", "Kishk (Egyptian)", "كشك", 110, 5, 12, 4.5, 1, { bowl: 250 }, "dishes"],
  ["bessara", "Bessara (fava & herb dip)", "بصارة", 110, 7, 15, 2.5, 5, { plate: 200, bowl: 200 }, "dishes"],
  ["ful-eskandarani", "Ful Alexandrian (with tomato & peppers)", "فول إسكندراني|فول اسكندراني", 115, 7, 17, 2.5, 5, { plate: 200 }, "dishes"],
  ["ful-oil", "Ful with oil (typical cart plate)", "فول بالزيت الحار|فول بالزيت", 150, 7.5, 19, 5, 5.2, { plate: 200 }, "dishes"],
  ["ful-tahini", "Ful with tahini", "فول بالطحينة", 160, 8.5, 18, 6.5, 5.5, { plate: 200 }, "dishes"],
  ["eggplant-salad", "Eggplant salad (mesaqa'a style)", "مسقعة|بتنجان مخلل", 110, 1.5, 9, 8, 3, { plate: 200 }, "dishes"],
  ["okra-veg", "Okra in tomato (no meat)", "بامية بالصلصة", 70, 2, 8, 3.5, 3, { plate: 250 }, "dishes"],
  ["peas-carrots-stew", "Peas & carrots stew with meat", "بسلة بالجزر|بسلة باللحمة", 95, 6, 9, 4, 3.5, { plate: 250 }, "dishes"],
  ["potato-stew", "Potato stew (batates bel salsa)", "بطاطس بالصلصة|طاجن بطاطس", 110, 3, 14, 5, 1.8, { plate: 250 }, "dishes"],
  ["zucchini-stew", "Zucchini stew", "كوسة بالصلصة|كوسة بالبشاميل", 70, 3, 6, 4, 1.5, { plate: 250 }, "dishes"],
  ["spinach-stew", "Spinach stew (sabanekh)", "سبانخ مطبوخة|سبانخ باللحمة", 80, 5, 5, 4.5, 2.5, { plate: 250 }, "dishes"],
  ["taro", "Taro stew (qolqas)", "قلقاس", 110, 3, 16, 4, 3, { plate: 250 }, "dishes"],
  ["freekeh-pigeon", "Stuffed pigeon with freekeh", "حمام محشي|حمام", 230, 16, 12, 13, 1.5, { piece: 300 }, "dishes"],
  ["stuffed-cabbage", "Stuffed cabbage rolls", "محشي كرنب", 135, 2.5, 21, 4.8, 2, { piece: 40, plate: 300 }, "dishes"],
  ["stuffed-vine", "Stuffed vine leaves", "ورق عنب|محشي ورق عنب", 150, 2.8, 23, 5.5, 2.5, { piece: 12, plate: 250 }, "dishes"],
  ["stuffed-pepper", "Stuffed peppers / zucchini / eggplant", "فلفل محشي|كوسة محشية|بتنجان محشي", 120, 3, 19, 3.8, 2, { piece: 120, plate: 300 }, "dishes"],
  ["mesaka", "Moussaka (eggplant with minced meat)", "مسقعة باللحمة|مسقعة", 140, 6, 8, 9.5, 2.5, { plate: 250 }, "dishes"],
  ["kofta-dawood", "Dawood basha (meatballs in tomato)", "داود باشا", 180, 11, 7, 12, 1, { plate: 250, piece: 35 }, "dishes"],
  ["chicken-panee", "Chicken pané (breaded, fried)", "فراخ بانيه|بانيه", 250, 20, 13, 13, 0.7, { piece: 110, plate: 200 }, "protein"],
  ["chicken-grilled-half", "Grilled chicken (half, with skin)", "نص فرخة مشوية|فرخة مشوية|فراخ مشوية بالجلد", 215, 26, 0, 12, 0, { half: 400, quarter: 200, piece: 200 }, "protein"],
  ["chicken-fried", "Fried chicken (with skin)", "فراخ مقلية|فرايد تشيكن|بروستد", 260, 24, 8, 15, 0.4, { piece: 130, plate: 300 }, "protein"],
  ["chicken-wings", "Chicken wings (grilled)", "جوانح|أجنحة فراخ|وينجز", 254, 24, 0, 17, 0, { piece: 35, plate: 200 }, "protein"],
  ["chicken-shish", "Shish tawook", "شيش طاووق", 180, 25, 3, 7.5, 0.3, { skewer: 120, plate: 250 }, "protein"],
  ["kebab", "Lamb kebab (grilled)", "كباب", 280, 24, 0, 20, 0, { skewer: 60, piece: 60, plate: 250 }, "protein"],
  ["lamb", "Lamb (cooked)", "لحم ضاني|ضاني|لحمة ضاني", 294, 25, 0, 21, 0, { portion: 150, piece: 100 }, "protein"],
  ["veal", "Veal (cooked, lean)", "بتلو|لحم بتلو", 196, 32, 0, 7, 0, { portion: 150 }, "protein"],
  ["beef-escalope", "Beef escalope (breaded)", "إسكالوب|اسكالوب", 260, 20, 12, 15, 0.5, { piece: 120 }, "protein"],
  ["duck", "Duck (roasted, with skin)", "بط|بطة", 337, 19, 0, 28, 0, { portion: 150 }, "protein"],
  ["turkey", "Turkey breast (roasted)", "ديك رومي|تركي", 135, 30, 0, 1, 0, { portion: 150, slice: 20 }, "protein"],
  ["rabbit", "Rabbit (cooked)", "أرانب|أرنب", 173, 33, 0, 3.5, 0, { portion: 150 }, "protein"],
  ["hotdog", "Hot dog sausage", "هوت دوج|سوسيس", 290, 10, 4, 26, 0, { piece: 45 }, "protein"],
  ["luncheon", "Luncheon meat", "لانشون", 230, 11, 7, 17, 0, { slice: 20 }, "protein"],
  ["pastrami", "Basterma", "بسطرمة", 250, 30, 2, 13, 0, { slice: 10 }, "protein"],
  ["smoked-turkey", "Smoked turkey slices", "تركي مدخن", 110, 18, 3, 3, 0, { slice: 20 }, "protein"],
  ["sardines", "Sardines (canned in oil)", "سردين", 208, 25, 0, 11.5, 0, { can: 90, piece: 12 }, "protein"],
  ["feseekh", "Fesikh (salted fish)", "فسيخ|ملوحة|رنجة", 210, 20, 0, 14, 0, { portion: 100, piece: 100 }, "protein"],
  ["herring", "Smoked herring", "رنجة مدخنة", 217, 25, 0, 12, 0, { piece: 100 }, "protein"],
  ["calamari", "Calamari (fried)", "كاليماري|سبيط مقلي", 175, 18, 8, 7.5, 0, { plate: 200 }, "protein"],
  ["mackerel", "Mackerel (cooked)", "ماكريل|سمك ماكريل", 262, 24, 0, 18, 0, { fillet: 150 }, "protein"],
  ["sea-bass", "Sea bass / bouri (grilled)", "قاروص|بوري|دنيس", 124, 23.6, 0, 2.6, 0, { fillet: 150, piece: 250 }, "protein"],
  ["fish-sayadeya", "Fish sayadeya (with rice)", "صيادية|سمك صيادية", 170, 12, 18, 5.5, 0.8, { plate: 350 }, "dishes"],
  ["crab", "Crab (cooked)", "كابوريا|سلطعون", 97, 19, 0, 1.5, 0, { portion: 150 }, "protein"],
  // ---- legumes & grains ----
  ["lentils", "Lentils (cooked)", "عدس مطبوخ|عدس أصفر|عدس بجبة", 116, 9, 20, 0.4, 7.9, { cup: 198, plate: 250, bowl: 250 }, "protein"],
  ["beans-white", "White beans stew (fasolia beida)", "فاصوليا بيضا|فاصوليا بيضاء", 130, 7.5, 18, 3, 6, { plate: 250 }, "dishes"],
  ["kidney-beans", "Kidney beans (cooked)", "فاصوليا حمرا|لوبيا", 127, 8.7, 22.8, 0.5, 7.4, { cup: 177 }, "protein"],
  ["black-eyed", "Black-eyed peas (cooked)", "لوبيا مطبوخة", 116, 7.7, 21, 0.5, 6.5, { cup: 172, plate: 250 }, "protein"],
  ["quinoa", "Quinoa (cooked)", "كينوا", 120, 4.4, 21.3, 1.9, 2.8, { cup: 185 }, "grains"],
  ["couscous", "Couscous (cooked)", "كسكسي|كسكس", 112, 3.8, 23, 0.2, 1.4, { cup: 157, plate: 200 }, "grains"],
  ["noodles", "Instant noodles (prepared)", "إندومي|اندومي|نودلز", 138, 3, 19, 5.5, 0.9, { pack: 240, bowl: 240 }, "grains"],
  ["basmati", "Basmati rice (cooked)", "رز بسمتي", 121, 3.5, 25, 0.4, 0.4, { cup: 160, plate: 200 }, "grains"],
  ["biryani", "Chicken biryani", "برياني|برياني فراخ", 170, 9, 21, 5.5, 1, { plate: 350 }, "dishes"],
  ["kabsa", "Chicken kabsa", "كبسة|كبسة فراخ", 165, 10, 19, 5.5, 0.8, { plate: 400 }, "dishes"],
  ["mandi", "Mandi (lamb / chicken with rice)", "مندي|منسف", 190, 12, 18, 7.5, 0.6, { plate: 400 }, "dishes"],
  ["maqluba", "Maqluba", "مقلوبة", 160, 7, 20, 6, 1.5, { plate: 350 }, "dishes"],
  ["tabbouleh", "Tabbouleh", "تبولة", 120, 2, 10, 8.5, 2.5, { plate: 150, bowl: 150 }, "veg"],
  ["fattoush", "Fattoush", "فتوش", 95, 2, 10, 5.5, 2.5, { plate: 200 }, "veg"],
  ["mujadara", "Mujadara (lentils & rice)", "مجدرة", 150, 6, 23, 4, 4.5, { plate: 300 }, "dishes"],
  ["pasta-red", "Pasta with red sauce", "مكرونة صلصة|مكرونة حمرا|اسباجتي بالصلصة", 130, 4.5, 23, 2.5, 1.8, { plate: 350 }, "dishes"],
  ["pasta-white", "Pasta Alfredo (white sauce)", "مكرونة وايت صوص|الفريدو", 190, 7, 22, 8.5, 1, { plate: 350 }, "dishes"],
  ["pasta-negresco", "Pasta Negresco", "مكرونة نجرسكو|نجرسكو", 200, 9, 18, 10, 0.8, { plate: 300 }, "dishes"],
  ["pasta-meat", "Pasta bolognese", "مكرونة بولونيز|مكرونة باللحمة المفرومة", 150, 7.5, 18, 5.5, 1.5, { plate: 350 }, "dishes"],
  ["lasagna", "Lasagna", "لازانيا", 165, 9, 15, 7.5, 1, { piece: 250 }, "dishes"],
  ["risotto", "Mushroom risotto", "ريزوتو", 140, 3.5, 20, 5, 0.8, { plate: 300 }, "dishes"],
  // ---- breads & bakery ----
  ["tortilla", "Tortilla wrap", "تورتيلا|راب", 310, 8, 51, 8, 3, { piece: 60 }, "grains"],
  ["pita-brown", "Whole wheat pita (small)", "عيش سن|عيش بني صغير", 250, 9.5, 50, 1.7, 7, { loaf: 55, piece: 55 }, "grains"],
  ["kaiser", "Burger bun", "عيش برجر|بان", 280, 9, 50, 4.5, 2.3, { piece: 60 }, "grains"],
  ["samoli", "Samoli bread", "عيش سمولي|سمولي", 270, 9, 53, 2.5, 2.5, { piece: 90 }, "grains"],
  ["crackers", "Crackers / rusk (bakery)", "بقسماط|كراكرز|كريكرز", 420, 10, 72, 9, 3, { piece: 10 }, "grains"],
  ["kahk", "Kahk (Eid cookies)", "كحك", 480, 6, 55, 26, 1, { piece: 30 }, "sweets"],
  ["ghorayeba", "Ghorayeba", "غريبة", 500, 5, 55, 29, 1, { piece: 20 }, "sweets"],
  ["petit-four", "Petit four", "بيتي فور", 490, 6, 60, 25, 1.5, { piece: 12 }, "sweets"],
  ["pie-cheese", "Cheese pastry (fatayer)", "فطاير جبنة|فطيرة جبنة|بف باستري", 330, 10, 32, 18, 1.2, { piece: 80 }, "grains"],
  ["pizza-pepperoni", "Pepperoni pizza", "بيتزا بيبروني", 290, 12, 32, 12.5, 2, { slice: 110 }, "dishes"],
  ["pizza-chicken", "Chicken ranch pizza", "بيتزا فراخ|بيتزا تشيكن رانش", 265, 13, 30, 10, 1.8, { slice: 110 }, "dishes"],
  ["manakish", "Manakish (zaatar)", "مناقيش|مناقيش زعتر", 330, 8, 40, 15, 3, { piece: 120 }, "grains"],
  ["bagel", "Bagel", "بيجل", 257, 10, 50, 1.6, 2.3, { piece: 100 }, "grains"],
  ["muffin", "Muffin", "مافن|كب كيك", 380, 5.5, 52, 17, 1.5, { piece: 110 }, "sweets"],
  ["donut", "Doughnut (glazed)", "دونات", 421, 5, 51, 22, 1.3, { piece: 60 }, "sweets"],
  ["waffle", "Waffle", "وافل", 290, 7.5, 33, 14, 1, { piece: 75 }, "sweets"],
  ["pancake", "Pancakes", "بان كيك|بانكيك", 227, 6.4, 28, 10, 0.9, { piece: 40 }, "sweets"],
  ["crepe", "Crepe (sweet, with chocolate)", "كريب|كريب نوتيلا", 290, 6, 36, 13, 1.5, { piece: 150 }, "sweets"],
  ["crepe-savory", "Crepe (savoury, chicken / meat)", "كريب فراخ|كريب لحمة|كريب سوسيس", 230, 12, 24, 9.5, 1, { piece: 250 }, "dishes"],
  // ---- fast food & restaurants ----
  ["big-burger", "Double burger with cheese", "دبل برجر|برجر دبل|تشيز برجر", 270, 15, 18, 15, 1, { piece: 260, sandwich: 260 }, "dishes"],
  ["chicken-burger", "Crispy chicken burger", "برجر فراخ|تشيكن برجر|زنجر", 250, 12, 25, 11.5, 1.5, { piece: 200, sandwich: 200 }, "dishes"],
  ["chicken-nuggets", "Chicken nuggets", "ناجتس|تشيكن ناجتس", 296, 15, 16, 19, 1, { piece: 16 }, "protein"],
  ["meat-shawarma", "Meat shawarma sandwich", "شاورما لحمة|ساندوتش شاورما لحمة", 250, 14, 22, 12, 1.5, { sandwich: 250 }, "dishes"],
  ["shawarma-plate", "Shawarma plate (with rice & fries)", "طبق شاورما|وجبة شاورما|فتة شاورما", 210, 11, 20, 9.5, 1.5, { plate: 450 }, "dishes"],
  ["fries-large", "Fries (large)", "بطاطس كبيرة", 312, 3.4, 41, 15, 3.8, { portion: 150 }, "grains"],
  ["onion-rings", "Onion rings", "حلقات بصل|أونيون رينجز", 411, 4.5, 38, 27, 2.4, { portion: 100 }, "grains"],
  ["hotdog-sandwich", "Hot dog sandwich", "ساندوتش هوت دوج", 290, 10, 24, 17, 1, { piece: 150 }, "dishes"],
  ["club-sandwich", "Club sandwich", "كلوب ساندوتش", 230, 13, 18, 12, 1.5, { piece: 250 }, "dishes"],
  ["tuna-sandwich", "Tuna sandwich", "ساندوتش تونة", 230, 12, 25, 9, 2, { piece: 180 }, "dishes"],
  ["cheese-sandwich", "Cheese sandwich (white cheese)", "ساندوتش جبنة|ساندوتش جبنة بيضا", 250, 10, 30, 10, 2, { piece: 130 }, "dishes"],
  ["egg-sandwich", "Egg sandwich", "ساندوتش بيض", 230, 10, 25, 10, 2, { piece: 150 }, "dishes"],
  ["pane-sandwich", "Chicken pané sandwich", "ساندوتش بانيه|بانيه ساندوتش", 260, 14, 27, 11, 1.5, { piece: 220 }, "dishes"],
  ["kofta-sandwich", "Kofta sandwich", "ساندوتش كفتة", 240, 12, 23, 11, 1.5, { piece: 200 }, "dishes"],
  ["sushi", "Sushi (maki)", "سوشي", 145, 5, 28, 1, 1, { piece: 25, roll: 150 }, "dishes"],
  ["fried-rice", "Chinese fried rice", "رز صيني|فرايد رايس", 175, 5, 25, 6, 1, { plate: 300 }, "dishes"],
  ["sweet-sour", "Sweet & sour chicken", "فراخ سويت اند ساور", 220, 11, 25, 8.5, 0.7, { plate: 300 }, "dishes"],
  ["tacos", "Tacos (beef)", "تاكو", 226, 9, 20, 12, 3, { piece: 100 }, "dishes"],
  ["burrito", "Burrito (chicken)", "بوريتو", 190, 10, 22, 7, 2.5, { piece: 300 }, "dishes"],
  ["caesar", "Caesar salad (with chicken)", "سلطة سيزر", 150, 11, 6, 9.5, 1.5, { plate: 300 }, "veg"],
  ["greek-salad", "Greek salad", "سلطة يوناني", 110, 3.5, 5, 8.5, 1.5, { plate: 250 }, "veg"],
  ["coleslaw", "Coleslaw", "كولسلو", 150, 1, 13, 10.5, 1.8, { cup: 100 }, "veg"],
  ["tahini-salad", "Tahini salad", "سلطة طحينة", 250, 7, 9, 21, 4, { tbsp: 15, plate: 100 }, "dishes"],
  ["pickles", "Pickles (torshi)", "طرشي|مخلل", 12, 0.5, 2, 0.2, 1.2, { piece: 30, plate: 100 }, "veg"],
  // ---- dairy & eggs ----
  ["cheddar", "Cheddar cheese", "شيدر|جبنة شيدر", 403, 25, 1.3, 33, 0, { slice: 20 }, "dairy"],
  ["halloumi", "Halloumi", "حلوم|حلومي", 321, 21, 2, 25, 0, { slice: 30 }, "dairy"],
  ["cream-cheese", "Cream cheese", "جبنة كريمي|كيري|جبنة كريمية", 342, 6, 4, 34, 0, { tbsp: 15, piece: 18 }, "dairy"],
  ["mish", "Mish (aged cheese)", "مش|جبنة قديمة", 280, 18, 3, 22, 0, { tbsp: 15 }, "dairy"],
  ["parmesan", "Parmesan", "بارميزان", 431, 38, 4, 29, 0, { tbsp: 5 }, "dairy"],
  ["yogurt-lowfat", "Yogurt (low fat)", "زبادي لايت|زبادي قليل الدسم", 56, 5.7, 7.7, 0.2, 0, { pot: 105, cup: 245 }, "dairy"],
  ["yogurt-fruit", "Fruit yogurt", "زبادي فواكه|زبادي بالفاكهة", 99, 3.5, 17, 1.5, 0.3, { pot: 120 }, "dairy"],
  ["laban-rayeb", "Buttermilk / rayeb / ayran", "لبن رايب|عيران|لبن زبادي", 40, 3.3, 4.8, 0.9, 0, { cup: 250, glass: 250 }, "dairy"],
  ["milk-semi", "Milk (semi-skimmed)", "لبن نص دسم|حليب نصف دسم", 47, 3.4, 4.8, 1.6, 0, { cup: 244, glass: 250 }, "dairy"],
  ["cream", "Cream (cooking)", "كريمة طبخ|كريمة", 195, 2.5, 4, 19, 0, { tbsp: 15 }, "dairy"],
  ["qeshta", "Qeshta (clotted cream)", "قشطة", 340, 2.5, 3, 36, 0, { tbsp: 15 }, "dairy"],
  ["condensed-milk", "Sweetened condensed milk", "لبن مكثف|لبن محلى", 321, 7.9, 54, 8.7, 0, { tbsp: 20 }, "dairy"],
  ["soy-milk", "Soy milk (unsweetened)", "لبن صويا", 33, 3.3, 0.6, 1.8, 0.3, { cup: 244 }, "dairy"],
  ["almond-milk", "Almond milk (unsweetened)", "لبن لوز", 15, 0.6, 0.3, 1.2, 0.2, { cup: 244 }, "dairy"],
  ["egg-scrambled", "Scrambled eggs (with butter)", "بيض مخفوق|بيض سكرامبل|بيض بالزبدة", 170, 11, 1.6, 13, 0, { piece: 60, plate: 150 }, "protein"],
  ["egg-pastrami", "Eggs with basterma", "بيض بسطرمة", 230, 15, 1.5, 18, 0, { plate: 150 }, "protein"],
  // ---- fruit (more) ----
  ["apricot", "Apricot", "مشمش", 48, 1.4, 11, 0.4, 2, { piece: 35 }, "fruit"],
  ["plum", "Plum", "برقوق", 46, 0.7, 11.4, 0.3, 1.4, { piece: 66 }, "fruit"],
  ["cherries", "Cherries", "كريز", 63, 1.1, 16, 0.2, 2.1, { cup: 138, piece: 8 }, "fruit"],
  ["pineapple", "Pineapple", "أناناس|اناناس", 50, 0.5, 13, 0.1, 1.4, { cup: 165, slice: 85 }, "fruit"],
  ["melon", "Cantaloupe / shamam", "كنتالوب|شمام", 34, 0.8, 8.2, 0.2, 0.9, { slice: 100, cup: 160 }, "fruit"],
  ["mandarin", "Mandarin / tangerine", "يوسفي|يوسف أفندي", 53, 0.8, 13, 0.3, 1.8, { piece: 88 }, "fruit"],
  ["grapefruit", "Grapefruit", "جريب فروت", 42, 0.8, 11, 0.1, 1.6, { half: 123 }, "fruit"],
  ["persimmon", "Persimmon (kaki)", "كاكا|كاكي", 70, 0.6, 18.6, 0.2, 3.6, { piece: 168 }, "fruit"],
  ["prickly-pear", "Prickly pear (teen shouki)", "تين شوكي", 41, 0.7, 9.6, 0.5, 3.6, { piece: 100 }, "fruit"],
  ["blueberries", "Blueberries", "توت أزرق|بلوبيري", 57, 0.7, 14.5, 0.3, 2.4, { cup: 148 }, "fruit"],
  ["mulberries", "Mulberries", "توت", 43, 1.4, 9.8, 0.4, 1.7, { cup: 140 }, "fruit"],
  ["raisins", "Raisins", "زبيب", 299, 3.1, 79, 0.5, 3.7, { tbsp: 10, handful: 30 }, "fruit"],
  ["dried-apricot", "Dried apricot (qamar el din sheet)", "مشمش مجفف|قمر الدين", 241, 3.4, 63, 0.5, 7.3, { piece: 8, sheet: 50 }, "fruit"],
  ["dried-figs", "Dried figs", "تين مجفف", 249, 3.3, 64, 0.9, 9.8, { piece: 20 }, "fruit"],
  ["coconut", "Coconut (fresh)", "جوز هند", 354, 3.3, 15, 33, 9, { piece: 45 }, "fruit"],
  ["lemon-whole", "Lemon", "ليمونة", 29, 1.1, 9.3, 0.3, 2.8, { piece: 60 }, "fruit"],
  ["fruit-salad", "Fruit salad", "سلطة فواكه|فروت سلاد", 50, 0.6, 12.5, 0.2, 1.5, { cup: 150, bowl: 250 }, "fruit"],
  // ---- vegetables (more) ----
  ["cauliflower", "Cauliflower", "قرنبيط", 25, 1.9, 5, 0.3, 2, { cup: 107 }, "veg"],
  ["cauliflower-fried", "Fried cauliflower", "قرنبيط مقلي", 190, 3, 12, 15, 2.5, { plate: 150 }, "veg"],
  ["cabbage", "Cabbage", "كرنب|ملفوف", 25, 1.3, 5.8, 0.1, 2.5, { cup: 89 }, "veg"],
  ["beetroot", "Beetroot (cooked)", "بنجر", 44, 1.7, 10, 0.2, 2, { piece: 80 }, "veg"],
  ["mushrooms", "Mushrooms", "مشروم|عيش الغراب", 22, 3.1, 3.3, 0.3, 1, { cup: 70 }, "veg"],
  ["eggplant", "Eggplant (grilled, no oil)", "بتنجان مشوي|باذنجان", 35, 0.8, 8.7, 0.2, 2.5, { piece: 250 }, "veg"],
  ["okra", "Okra", "بامية خضرا", 33, 1.9, 7, 0.2, 3.2, { cup: 100 }, "veg"],
  ["green-beans", "Green beans", "فاصوليا خضرا ني|فاصوليا خضراء", 31, 1.8, 7, 0.2, 2.7, { cup: 100 }, "veg"],
  ["rocket", "Rocket (gargeer)", "جرجير", 25, 2.6, 3.7, 0.7, 1.6, { bunch: 50 }, "veg"],
  ["parsley", "Parsley / coriander / dill", "بقدونس|كزبرة|شبت", 36, 3, 6.3, 0.8, 3.3, { bunch: 30 }, "veg"],
  ["radish", "Radish", "فجل", 16, 0.7, 3.4, 0.1, 1.6, { piece: 10 }, "veg"],
  ["hot-pepper", "Hot pepper", "شطة|فلفل حامي|فلفل أخضر حار", 40, 2, 9, 0.2, 1.5, { piece: 15 }, "veg"],
  ["olives", "Olives", "زيتون", 145, 1, 3.8, 15, 3.3, { piece: 4, handful: 30 }, "fats"],
  ["corn-cup", "Corn (canned)", "ذرة معلبة", 81, 2.6, 18, 1, 2, { cup: 165, tbsp: 15 }, "grains"],
  ["vegetable-soup", "Vegetable soup", "شوربة خضار", 45, 1.5, 7, 1.2, 1.5, { bowl: 300 }, "dishes"],
  ["chicken-soup", "Chicken soup (with noodles)", "شوربة فراخ|شوربة لسان عصفور", 45, 3, 5, 1.5, 0.3, { bowl: 300 }, "dishes"],
  ["tomato-soup", "Tomato soup", "شوربة طماطم", 40, 1, 7, 1, 1, { bowl: 300 }, "dishes"],
  ["mushroom-soup", "Cream of mushroom soup", "شوربة مشروم|كريمة مشروم", 75, 1.5, 6, 5, 0.5, { bowl: 300 }, "dishes"],
  ["freekeh-soup", "Freekeh soup", "شوربة فريك", 60, 3, 9, 1.5, 2, { bowl: 300 }, "dishes"],
  ["orzo-soup", "Orzo soup (lesan asfour)", "شوربة لسان عصفور باللحمة", 65, 3.5, 9, 1.8, 0.5, { bowl: 300 }, "dishes"],
  // ---- fats, sauces, condiments ----
  ["mayonnaise", "Mayonnaise", "مايونيز", 680, 1, 0.6, 75, 0, { tbsp: 14 }, "fats"],
  ["ketchup", "Ketchup", "كاتشب", 112, 1.2, 26, 0.1, 0.3, { tbsp: 17 }, "fats"],
  ["mustard", "Mustard", "مستردة|مسطردة", 66, 4.4, 5.8, 4, 3.3, { tsp: 5 }, "fats"],
  ["bbq-sauce", "Barbecue sauce", "صوص باربكيو", 172, 0.8, 41, 0.6, 0.9, { tbsp: 17 }, "fats"],
  ["garlic-sauce", "Garlic sauce (toum)", "صوص توم|ثومية|تومية", 500, 1, 5, 53, 0.3, { tbsp: 15 }, "fats"],
  ["ranch", "Ranch dressing", "رانش", 430, 1, 6, 44, 0, { tbsp: 15 }, "fats"],
  ["nutella", "Chocolate hazelnut spread", "نوتيلا|شوكولاتة دهن", 539, 6.3, 57.5, 31, 3.4, { tbsp: 19 }, "sweets"],
  ["halawa", "Halawa (tahini halva)", "حلاوة طحينية|حلاوة", 520, 12, 50, 30, 4, { tbsp: 20, piece: 30 }, "sweets"],
  ["molasses", "Molasses (black honey)", "عسل أسود", 290, 0, 75, 0.1, 0, { tbsp: 20 }, "sweets"],
  ["sesame", "Sesame seeds", "سمسم", 573, 17.7, 23, 49.7, 11.8, { tbsp: 9 }, "fats"],
  ["sunflower-seeds", "Sunflower seeds (lebb)", "لب سوري|لب أبيض|لب", 584, 21, 20, 51, 8.6, { handful: 30 }, "fats"],
  ["pumpkin-seeds", "Pumpkin seeds", "لب أبيض قرع|بذور قرع", 559, 30, 11, 49, 6, { handful: 30 }, "fats"],
  ["cashews", "Cashews", "كاجو", 553, 18, 30, 44, 3.3, { handful: 28 }, "fats"],
  ["pistachio", "Pistachios", "فستق|فزدق", 560, 20, 28, 45, 10.6, { handful: 28 }, "fats"],
  ["hazelnuts", "Hazelnuts", "بندق", 628, 15, 17, 61, 9.7, { handful: 28 }, "fats"],
  ["chia", "Chia seeds", "بذور شيا|شيا", 486, 17, 42, 31, 34, { tbsp: 12 }, "fats"],
  ["flax", "Flax seeds", "بذر كتان|كتان", 534, 18, 29, 42, 27, { tbsp: 10 }, "fats"],
  ["coconut-oil", "Coconut oil", "زيت جوز هند", 892, 0, 0, 99, 0, { tbsp: 13.6 }, "fats"],
  // ---- sweets & snacks (more) ----
  ["baklava", "Baklava", "بقلاوة", 430, 6.7, 37, 29, 2.5, { piece: 30 }, "sweets"],
  ["zalabya", "Zalabya / luqaimat", "زلابية|لقمة القاضي|لقيمات", 390, 4, 55, 17, 1, { piece: 15 }, "sweets"],
  ["qatayef", "Qatayef (fried, with nuts)", "قطايف", 330, 6, 45, 14, 1.5, { piece: 60 }, "sweets"],
  ["meshabek", "Meshabek", "مشبك", 430, 2, 70, 16, 0.5, { piece: 25 }, "sweets"],
  ["mahalabiya", "Mahalabiya", "مهلبية", 120, 3.5, 20, 3, 0, { cup: 150 }, "sweets"],
  ["sobia", "Sobia", "سوبيا", 80, 1.5, 16, 1.5, 0, { glass: 250 }, "drinks"],
  ["khoshaf", "Khoshaf (dried fruit in syrup)", "خشاف", 110, 1.2, 27, 0.5, 2.5, { bowl: 200 }, "sweets"],
  ["ice-lolly", "Ice lolly", "آيس كريم مصاصة|مصاصة", 80, 0, 20, 0, 0, { piece: 60 }, "sweets"],
  ["popcorn", "Popcorn (with oil)", "فشار|بوب كورن", 500, 9, 58, 28, 10, { cup: 11, bag: 60 }, "sweets"],
  ["gum-candy", "Candy / jelly sweets", "حلويات جيلي|بونبون|كاندي", 350, 2, 88, 0, 0, { piece: 5, bag: 40 }, "sweets"],
  ["wafer", "Wafer bar (chocolate)", "ويفر|كيت كات|تويكس", 520, 6, 62, 27, 2, { bar: 42, piece: 21 }, "sweets"],
  ["protein-bar", "Protein bar", "بروتين بار", 370, 30, 40, 11, 5, { bar: 60 }, "protein"],
  ["granola", "Granola", "جرانولا", 471, 10, 64, 20, 5.3, { cup: 60, tbsp: 8 }, "grains"],
  ["granola-bar", "Granola / oat bar", "بار شوفان|جرانولا بار", 430, 8, 64, 15, 4, { bar: 35 }, "grains"],
  ["rice-cake", "Rice cakes", "رايس كيك|كعك رز", 387, 8, 81, 2.8, 4.2, { piece: 9 }, "grains"],
  ["dates-paste", "Date paste (agwa)", "عجوة", 300, 2, 75, 0.5, 7, { tbsp: 20 }, "fruit"],
  ["sugar-brown", "Brown sugar", "سكر بني", 380, 0.1, 98, 0, 0, { tsp: 4 }, "sweets"],
  ["sweetener", "Sweetener (stevia / sucralose)", "سكر دايت|محلي صناعي|ستيفيا", 0, 0, 0, 0, 0, { tsp: 1, piece: 1 }, "sweets"],
  // ---- drinks (per 100 ml, more) ----
  ["tea-sugar", "Tea with sugar (2 tsp)", "شاي بسكر|شاي بالسكر|شاي سكر", 14, 0, 3.4, 0, 0, { cup: 240, glass: 240 }, "drinks"],
  ["mint-tea", "Mint tea with sugar", "شاي بالنعناع", 14, 0, 3.4, 0, 0, { cup: 240 }, "drinks"],
  ["green-tea", "Green tea", "شاي أخضر|شاي اخضر", 1, 0, 0.2, 0, 0, { cup: 240 }, "drinks"],
  ["anise", "Anise / herbal tea", "ينسون|كركديه ساقع من غير سكر|أعشاب|قرفة|نعناع", 2, 0, 0.4, 0, 0, { cup: 240 }, "drinks"],
  ["nescafe", "Instant coffee with milk & sugar", "نسكافيه|نيسكافيه|3 في 1", 45, 1.2, 7.5, 1.3, 0, { cup: 240, sachet: 200 }, "drinks"],
  ["iced-coffee", "Iced coffee (sweetened, with milk)", "آيس كوفي|قهوة ساقعة|فرابيه", 70, 1.8, 11, 2, 0, { cup: 350 }, "drinks"],
  ["mocha", "Mocha", "موكا", 75, 2.8, 10, 2.8, 0.5, { cup: 350 }, "drinks"],
  ["hot-chocolate", "Hot chocolate", "هوت شوكليت|شوكولاتة سخنة", 77, 3.5, 11, 2.3, 0.7, { cup: 250 }, "drinks"],
  ["sahlab", "Sahlab", "سحلب", 100, 3, 16, 2.8, 0, { cup: 250 }, "drinks"],
  ["mango-juice", "Mango juice", "عصير مانجا", 57, 0.3, 14, 0.1, 0.3, { glass: 250 }, "drinks"],
  ["guava-juice", "Guava juice", "عصير جوافة", 60, 0.3, 15, 0.1, 1, { glass: 250 }, "drinks"],
  ["lemon-mint", "Lemon mint juice (sweetened)", "ليمون نعناع|ليمون بالنعناع|عصير ليمون", 45, 0.1, 11.5, 0, 0.1, { glass: 300 }, "drinks"],
  ["tamarind", "Tamarind drink", "تمر هندي", 55, 0.1, 14, 0, 0, { glass: 250 }, "drinks"],
  ["qamar-drink", "Qamar el din drink", "عصير قمر الدين", 70, 0.4, 17, 0, 0.8, { glass: 250 }, "drinks"],
  ["smoothie", "Fruit smoothie", "سموذي", 60, 0.9, 14, 0.2, 1.2, { glass: 350 }, "drinks"],
  ["milkshake", "Milkshake", "ميلك شيك", 112, 3.4, 18, 3, 0.2, { glass: 350 }, "drinks"],
  ["energy-drink", "Energy drink", "مشروب طاقة|ريد بول|باور هورس", 45, 0, 11, 0, 0, { can: 250 }, "drinks"],
  ["diet-cola", "Diet cola", "كولا دايت|بيبسي دايت|كوكاكولا زيرو", 0, 0, 0, 0, 0, { can: 330 }, "drinks"],
  ["sparkling", "Sparkling water", "مياه فوارة|صودا", 0, 0, 0, 0, 0, { can: 330 }, "drinks"],
  ["juice-box", "Juice box (sweetened)", "عصير علبة|جهينة|عصير كرتونة", 50, 0.2, 12.5, 0, 0.1, { box: 235, can: 235 }, "drinks"],
  ["beer-free", "Malt drink (alcohol-free)", "بيريل|مشروب شعير", 40, 0.3, 9.5, 0, 0, { can: 330 }, "drinks"],
];

// ---- more recipes (per the whole recipe; `serves` splits it) ----
export const MORE_RECIPES = [
  { id: "egypt-breakfast", en: "Egyptian breakfast plate", ar: "فطار مصري", serves: 1, mins: 10, tags: ["breakfast", "egyptian"],
    items: [["ful", 150], ["taameya", 51], ["egg", 50], ["feta", 30], ["salad", 100], ["baladi", 90]], steps: ["Plate the ful, three taameya and a boiled egg.", "Add white cheese and salad.", "One baladi loaf."] },
  { id: "light-fatta", en: "Lighter fatta", ar: "فتة لايت", serves: 4, mins: 50, tags: ["lunch", "egyptian"],
    items: [["rice-dry", 200], ["baladi", 90], ["veal", 400], ["tomato-paste", 48], ["garlic", 15], ["olive-oil", 14]], steps: ["Cook rice; toast the bread in the oven instead of frying.", "Boil the veal and keep the broth.", "Garlic-vinegar tomato sauce with one spoon of oil.", "Layer bread, a little broth, rice, sauce, meat."] },
  { id: "chicken-mushroom", en: "Chicken with mushrooms", ar: "فراخ بالمشروم", serves: 2, mins: 25, tags: ["dinner", "high-protein", "low-carb"],
    items: [["chicken-raw", 360], ["mushrooms", 200], ["onion", 100], ["cream", 60], ["olive-oil", 10]], steps: ["Brown the chicken strips in the oil.", "Add onion and mushrooms; cook 5 min.", "Stir in the cream; season."] },
  { id: "beef-stirfry", en: "Beef & vegetable stir-fry", ar: "لحمة سوتيه بالخضار", serves: 2, mins: 20, tags: ["dinner", "high-protein"],
    items: [["beef", 250], ["pepper", 150], ["broccoli", 150], ["carrot", 80], ["olive-oil", 10], ["rice", 300]], steps: ["Stir-fry the beef strips hot and fast.", "Add the vegetables; 4 min.", "Soy sauce, garlic, ginger; serve on rice."] },
  { id: "salmon-quinoa", en: "Salmon with quinoa", ar: "سلمون بالكينوا", serves: 1, mins: 25, tags: ["dinner", "high-protein"],
    items: [["salmon", 150], ["quinoa", 150], ["spinach", 60], ["lemon", 15], ["olive-oil", 5]], steps: ["Bake the salmon 12 min at 200 °C.", "Serve on quinoa with wilted spinach and lemon."] },
  { id: "chickpea-salad", en: "Chickpea salad", ar: "سلطة حمص الشام", serves: 2, mins: 10, tags: ["lunch", "vegetarian", "high-fibre"],
    items: [["chickpeas", 250], ["tomato", 120], ["cucumber", 120], ["onion", 40], ["parsley", 20], ["olive-oil", 14], ["lemon", 30]], steps: ["Mix everything.", "Season with cumin, salt, lemon."] },
  { id: "lentil-salad", en: "Lentil salad", ar: "سلطة عدس", serves: 2, mins: 30, tags: ["lunch", "vegetarian", "high-fibre"],
    items: [["lentils", 300], ["tomato", 120], ["pepper", 80], ["parsley", 20], ["olive-oil", 14], ["lemon", 30]], steps: ["Cook brown lentils until just tender; cool.", "Mix with the chopped vegetables, oil and lemon."] },
  { id: "tuna-pasta", en: "Tuna pasta", ar: "مكرونة بالتونة", serves: 2, mins: 20, tags: ["lunch", "high-protein"],
    items: [["pasta-dry", 160], ["tuna-water", 240], ["tomato", 250], ["onion", 60], ["olive-oil", 10], ["garlic", 6]], steps: ["Cook the pasta.", "Tomato sauce with onion and garlic.", "Stir in the tuna and pasta."] },
  { id: "chicken-fajita", en: "Chicken fajita wraps", ar: "راب فاهيتا فراخ", serves: 2, mins: 20, tags: ["lunch", "high-protein"],
    items: [["chicken-raw", 300], ["pepper", 200], ["onion", 100], ["tortilla", 120], ["yogurt", 60], ["olive-oil", 10]], steps: ["Fry the chicken strips with fajita spice.", "Add peppers and onion.", "Wrap in the tortillas with a spoon of yogurt."] },
  { id: "egg-muffins", en: "Egg muffins (make ahead)", ar: "مافن بيض", serves: 3, mins: 25, tags: ["breakfast", "high-protein", "low-carb"],
    items: [["egg", 300], ["spinach", 60], ["pepper", 80], ["feta", 60]], steps: ["Whisk eggs; add chopped spinach, pepper and cheese.", "Pour into a muffin tray; bake 18 min at 180 °C.", "Keep 3 days in the fridge."] },
  { id: "cottage-toast", en: "Cottage cheese toast", ar: "توست بالجبنة القريش", serves: 1, mins: 5, tags: ["breakfast", "high-protein"],
    items: [["toast-brown", 60], ["cottage", 100], ["tomato", 60], ["cucumber", 60]], steps: ["Toast two slices.", "Spread the cottage cheese; top with tomato and cucumber, pepper and dried mint."] },
  { id: "chicken-soup-veg", en: "Chicken & vegetable soup", ar: "شوربة فراخ بالخضار", serves: 4, mins: 40, tags: ["dinner", "high-protein"],
    items: [["chicken-raw", 400], ["carrot", 150], ["zucchini", 200], ["potato", 200], ["onion", 100]], steps: ["Simmer the chicken with onion 20 min.", "Add the vegetables; 15 min more.", "Shred the chicken back in."] },
  { id: "moussaka-light", en: "Lighter moussaka", ar: "مسقعة لايت", serves: 4, mins: 50, tags: ["dinner", "egyptian"],
    items: [["eggplant", 800], ["beef-mince-raw", 250], ["tomato", 400], ["pepper", 150], ["onion", 100], ["olive-oil", 14]], steps: ["Grill the eggplant slices instead of frying.", "Brown the mince with onion; add tomato and pepper.", "Layer and bake 25 min."] },
  { id: "stuffed-pepper-light", en: "Stuffed peppers with rice & mince", ar: "فلفل محشي بالرز واللحمة", serves: 4, mins: 60, tags: ["lunch", "egyptian"],
    items: [["pepper", 600], ["rice-dry", 150], ["beef-mince-raw", 200], ["tomato", 300], ["onion", 80], ["olive-oil", 10]], steps: ["Mix rice, mince, grated onion, herbs and some tomato.", "Fill the peppers; simmer in the rest of the tomato 40 min."] },
  { id: "koshary-bowl", en: "High-protein koshari bowl", ar: "كشري بروتين", serves: 2, mins: 30, tags: ["lunch", "egyptian", "high-protein"],
    items: [["lentils", 300], ["rice", 200], ["chickpeas", 100], ["chicken-breast", 150], ["tomato-paste", 32], ["onion", 100], ["olive-oil", 10]], steps: ["Warm lentils, rice and chickpeas.", "Tomato-garlic-vinegar sauce.", "Top with sliced grilled chicken and baked onions."] },
  { id: "hummus-chicken", en: "Hummus with chicken", ar: "حمص بالفراخ", serves: 1, mins: 15, tags: ["lunch", "high-protein"],
    items: [["hummus", 120], ["chicken-breast", 120], ["shami", 60], ["salad", 100]], steps: ["Spread hummus on a plate.", "Top with warm sliced chicken, paprika and a drizzle of lemon.", "Pita and salad on the side."] },
  { id: "tabbouleh-meal", en: "Tabbouleh with grilled halloumi", ar: "تبولة مع حلوم مشوي", serves: 1, mins: 15, tags: ["lunch", "vegetarian"],
    items: [["tabbouleh", 200], ["halloumi", 60], ["pita-brown", 55]], steps: ["Grill the halloumi slices.", "Serve on the tabbouleh with the pita."] },
  { id: "shrimp-rice", en: "Shrimp with rice", ar: "جمبري بالرز", serves: 2, mins: 25, tags: ["dinner", "high-protein"],
    items: [["shrimp", 300], ["rice", 300], ["tomato", 200], ["garlic", 9], ["olive-oil", 10]], steps: ["Sauté garlic in oil; add tomato.", "Add shrimp for 3–4 minutes.", "Serve over rice."] },
  { id: "liver-onions", en: "Liver with onions & peppers", ar: "كبدة بالبصل والفلفل", serves: 2, mins: 15, tags: ["dinner", "high-protein"],
    items: [["liver", 300], ["onion", 150], ["pepper", 150], ["olive-oil", 10]], steps: ["Fry the liver strips fast in hot oil with garlic and cumin.", "Add onion and pepper; 3 min.", "Lemon to serve."] },
  { id: "oat-porridge", en: "Oat porridge with dates", ar: "بليلة شوفان بالبلح", serves: 1, mins: 8, tags: ["breakfast", "vegetarian"],
    items: [["oats", 50], ["milk-semi", 250], ["dates", 24], ["walnuts", 10]], steps: ["Cook oats in milk 5 min.", "Top with chopped dates and walnuts."] },
  { id: "belila", en: "Belila (wheat with milk)", ar: "بليلة", serves: 2, mins: 10, tags: ["breakfast", "egyptian"],
    items: [["bulgur", 300], ["milk", 400], ["sugar", 16], ["raisins", 20]], steps: ["Warm the cooked wheat in milk.", "Sweeten lightly; raisins and cinnamon."] },
  { id: "fruit-yogurt-bowl", en: "Fruit & yogurt bowl", ar: "بول زبادي بالفواكه", serves: 1, mins: 5, tags: ["snack", "vegetarian"],
    items: [["yogurt", 200], ["banana", 60], ["strawberries", 80], ["granola", 25]], steps: ["Yogurt in a bowl; fruit and granola on top."] },
  { id: "peanut-toast", en: "Peanut butter banana toast", ar: "توست زبدة فول سوداني وموز", serves: 1, mins: 5, tags: ["breakfast", "snack"],
    items: [["toast-brown", 60], ["peanut-butter", 16], ["banana", 60]], steps: ["Toast, spread, slice the banana on top."] },
  { id: "chicken-molokhia-light", en: "Molokhia (home, light)", ar: "ملوخية بيتي لايت", serves: 4, mins: 30, tags: ["lunch", "egyptian"],
    items: [["molokhia-leaves", 500], ["garlic", 15], ["olive-oil", 14]], steps: ["Simmer the minced leaves in chicken broth.", "Tasha: garlic and coriander fried in one spoon of oil.", "Serve with chicken breast and rice (log them too)."] },
  { id: "grilled-kofta-rice", en: "Kofta with rice & tahini", ar: "كفتة مع رز وطحينة", serves: 1, mins: 25, tags: ["dinner", "high-protein"],
    items: [["kofta", 160], ["rice", 150], ["tahini-salad", 40], ["salad", 150]], steps: ["Grill the kofta.", "Serve with rice, tahini and salad."] },
  { id: "fish-sayadeya-light", en: "Lighter sayadeya", ar: "صيادية لايت", serves: 3, mins: 45, tags: ["lunch", "egyptian", "high-protein"],
    items: [["fish-raw", 500], ["rice-dry", 200], ["onion", 200], ["olive-oil", 20], ["tomato-paste", 32]], steps: ["Brown the onion slowly in oil for colour.", "Cook the rice in the onion-fish broth.", "Bake the fish on top 20 min."] },
  { id: "potato-egg-tray", en: "Potato & egg tray (shakshuka style)", ar: "صينية بطاطس بالبيض", serves: 2, mins: 30, tags: ["breakfast", "vegetarian"],
    items: [["potato", 400], ["egg", 200], ["tomato", 200], ["onion", 80], ["olive-oil", 10]], steps: ["Roast potato cubes with oil 20 min.", "Add tomato and onion; crack in the eggs; bake until set."] },
  { id: "gym-chicken-sweetpotato", en: "Gym plate: chicken, sweet potato, broccoli", ar: "طبق جيم: فراخ وبطاطا وبروكلي", serves: 1, mins: 30, tags: ["lunch", "high-protein"],
    items: [["chicken-breast", 200], ["sweet-potato", 200], ["broccoli", 150], ["olive-oil", 5]], steps: ["Grill the chicken.", "Bake the sweet potato.", "Steam the broccoli."] },
  { id: "keto-plate", en: "Keto plate: eggs, avocado, halloumi", ar: "طبق كيتو: بيض وأفوكادو وحلوم", serves: 1, mins: 10, tags: ["breakfast", "low-carb"],
    items: [["egg-fried", 92], ["avocado", 75], ["halloumi", 50], ["salad", 100]], steps: ["Fry the eggs; grill the halloumi.", "Serve with avocado and salad."] },
  { id: "overnight-chia", en: "Chia pudding", ar: "بودنج شيا", serves: 1, mins: 5, tags: ["breakfast", "vegetarian", "high-fibre"],
    items: [["chia", 24], ["milk-skim", 200], ["honey", 7], ["mango", 80]], steps: ["Stir the chia into the milk and honey.", "Fridge overnight; mango on top."] },
  { id: "tuna-wrap", en: "Tuna wrap", ar: "راب تونة", serves: 1, mins: 5, tags: ["lunch", "high-protein"],
    items: [["tortilla", 60], ["tuna-water", 120], ["lettuce", 40], ["tomato", 60], ["yogurt", 30]], steps: ["Mix the tuna with yogurt and pepper.", "Wrap with lettuce and tomato."] },
  { id: "lentil-kofta", en: "Lentil patties (baked)", ar: "كفتة عدس بالفرن", serves: 3, mins: 40, tags: ["lunch", "vegetarian", "high-fibre"],
    items: [["lentils", 400], ["onion", 100], ["bulgur", 150], ["parsley", 20], ["olive-oil", 10]], steps: ["Mash lentils with bulgur, onion and herbs.", "Shape patties; bake 20 min at 200 °C."] },
  { id: "chicken-pane-oven", en: "Oven chicken pané", ar: "بانيه فراخ بالفرن", serves: 2, mins: 30, tags: ["dinner", "high-protein"],
    items: [["chicken-raw", 350], ["egg", 50], ["crackers", 50], ["olive-oil", 10]], steps: ["Dip the fillets in egg, then crushed rusk.", "Spray with oil; bake 18 min at 220 °C, turning once."] },
  { id: "beef-kofta-bowl", en: "Kofta bowl with bulgur", ar: "بول كفتة بالبرغل", serves: 1, mins: 25, tags: ["dinner", "high-protein"],
    items: [["kofta", 120], ["bulgur", 150], ["salad", 150], ["yogurt", 60]], steps: ["Grill kofta; serve on bulgur with salad and yogurt-mint sauce."] },
  { id: "veg-omelette-bread", en: "Omelette sandwich", ar: "ساندوتش أومليت", serves: 1, mins: 10, tags: ["breakfast"],
    items: [["egg", 100], ["pepper", 40], ["tomato", 40], ["olive-oil", 5], ["baladi", 90]], steps: ["Cook the omelette with the vegetables.", "Fill the baladi loaf."] },
  { id: "salad-meal", en: "Big protein salad", ar: "سلطة بروتين كبيرة", serves: 1, mins: 10, tags: ["lunch", "high-protein", "low-carb"],
    items: [["lettuce", 100], ["chicken-breast", 150], ["egg", 50], ["corn-cup", 50], ["tomato", 80], ["cucumber", 80], ["olive-oil", 7]], steps: ["Chop and toss everything with lemon and the oil."] },
  { id: "sahlab-light", en: "Sahlab (light)", ar: "سحلب لايت", serves: 1, mins: 8, tags: ["snack"],
    items: [["milk-skim", 250], ["sugar", 8], ["coconut", 10], ["pistachio", 10]], steps: ["Whisk sahlab powder into warm skimmed milk.", "Top with coconut and pistachio."] },
];
