// v6.12 — notes from another notes app into Shelf: shared/pasted text, Keep, Evernote, web pages, Word, zip.
const I = await import("../../web-src/shelf-import.js");
const C = await import("../../web-src/convert.js");
let fail = 0; const ok = (c, w) => { console.log((c ? "PASS " : "FAIL ") + w); if (!c) fail++; };
const one = I.notesFromText("Shopping\nmilk\nbread");
ok(one.length === 1 && one[0].title === "Shopping" && /bread/.test(one[0].text), "one shared note: first line is its title");
const sep = I.notesFromText("Crane 50 t\nservice on Sunday\n\n---\n\nCall Karim\nabout the invoice");
ok(sep.length === 2 && sep[1].title === "Call Karim", "notes split on --- lines");
const gaps = I.notesFromText("first note\nline\n\n\n\nsecond note\nline");
ok(gaps.length === 2 && gaps[1].title === "second note", "notes split on several empty lines");
const md = I.notesFromText("# Book\n## A\nalpha\n## B\nbeta");
ok(md.length === 2 && md[0].title === "A" && md[1].text === "beta", "## headings: one note each");
ok(I.notesFromText("ملاحظة الموقع\nالونش يوصل السبت")[0].title === "ملاحظة الموقع", "Arabic note");
const k = I.keepJson({ title: "", textContent: "Buy diesel", listContent: [{ text: "oil filter", isChecked: true }], createdTimestampUsec: "1727000000000000", labels: [{ name: "site" }] }, "x.json");
ok(k.title === "Buy diesel" && /- \[x\] oil filter/.test(k.text) && k.created === 1727000000000 && k.tags[0] === "site", "Google Keep JSON: text, checklist, date, labels");
ok(I.keepJson({ title: "old", isTrashed: true }) === null, "a trashed Keep note is skipped");
const en = I.enexNotes(`<?xml version="1.0"?><en-export><note><title>Meeting</title><content><![CDATA[<en-note><div>Agenda</div><div><en-todo checked="true"/>prices</div></en-note>]]></content><created>20260901T080000Z</created></note><note><title>Two</title><content><![CDATA[<en-note>b</en-note>]]></content></note></en-export>`);
ok(en.length === 2 && en[0].title === "Meeting" && /- \[x\] prices/.test(en[0].text) && en[0].created === Date.UTC(2026, 8, 1, 8), "Evernote .enex: two notes, checklist, date");
const h = I.htmlNote('<html><head><title>Plan</title></head><body><h1>Plan</h1><p>Step one &amp; two</p><ul><li>a</li><li>b</li></ul></body></html>');
ok(h.title === "Plan" && /Step one & two/.test(h.text) && /- a/.test(h.text) && !/^Plan/.test(h.text), "a web page note");
const enc = (s) => new TextEncoder().encode(s);
const tools = { unzip: async () => new Map([["notes/a.txt", enc("Alpha\nbody")], ["notes/b.md", enc("# Beta\nbody b")], ["notes/pic.jpg", enc("x")], ["__MACOSX/x", enc("y")]]), docxRead: C.docxRead, blocksToText: C.blocksToText };
const z = await I.notesFromFile("Notebook export.zip", new Uint8Array([1]), tools);
ok(z.length === 2 && z.map((x) => x.title).sort().join() === "Alpha,Beta", "a .zip of notes: each text file is a note, pictures and junk skipped");
let docx = C.docxFromBlocks([{ type: "h1", text: "Site visit" }, { type: "p", text: "Ground is soft." }], "visit"); if (docx && docx.then) docx = await docx; if (docx instanceof Blob) docx = new Uint8Array(await docx.arrayBuffer());
const d = await I.notesFromFile("visit.docx", docx, tools);
ok(d.length === 1 && /Ground is soft/.test(d[0].text), "a Word document from Notebook's \"export as document\"");
ok(I.isImage("IMG_1.JPG") && I.isImage("x", "image/png") && !I.isImage("a.txt"), "pictures are recognised");
console.log(fail ? `${fail} FAILED` : "ALL PASSED");
